### ISSUE TITLE
Error message typo

### ISSUE THREAD

**Issue by atanas-bitrise** [bitrise-steplib/steps-generate-shared-scheme#14]
### Troubleshooting

- [ ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.2.3
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

There is a typo in the error message:

The newly generated schemes, may differs from the ones in your project.

The correct wording should be:

The newly generated schemes, may differ from the ones in your project.

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

Run the step with projects settings that would trigger the error message.

**Comment by lpusok** [comment]
Hello @atanas-bitrise,
Can you also open a PR please?

**Comment by atanas-bitrise** [comment]
Hi @lpusok. I tried to push a branch but I don't seem to have the write permission for this repo. If an admin can grant me write privileges, I can push the branch and make a pull request. Thanks!

**Comment by atanas-bitrise** [comment]
@lpusok I forked the repository and I created the pull request from the fork. Thanks!

**Comment by lpusok** [comment]
Resolved.
